// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvrzjaoelfnriaxcqbkm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2cnpqYW9lbGZucmlheGNxYmttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyNTAzMzMsImV4cCI6MjA5NzgyNjMzM30.AprntNtEeCV3RsPRYN7LrcMfldP8x1zk-P7FIDCOre8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});